import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/core/components/pages/footer";
import Navbar from "@/core/components/pages/navbar";
import AuthProvider from "@/core/providers/AuthProvider";
import { ThemeContextProvider } from "@/core/contexts/ThemeContext";
import ThemeProvider from "@/core/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="containers">
          <div className="wrapper">
            <AuthProvider>
              <ThemeContextProvider>
                <ThemeProvider>
                  <Navbar />
                  {children}
                  <Footer />
                </ThemeProvider>
              </ThemeContextProvider>
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
